version: '3.3'
services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: 'fortune_cookies'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - "./init:/docker-entrypoint-initdb.d"
      - "./config/my.conf:/etc/mysql/conf.d/config-file.cnf"
      - "./data:/var/lib/mysql:rw"
      - "./hold:/etc/hold/"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  receiver:
    image: reselbob/receiver
    restart: always
    ports:
      -3030:3030
